### ISSUE TITLE
Question: nested configurations

### ISSUE THREAD

**Issue by f8ttyc8t** [randy3k/SyntaxManager#11]
Started using this great tool - awesome!

I'm using ST on different platforms, so my settings may differ by platform.
But they might differ not only by platform but by e.g. scope also.

E.g. markdown has font size 10 on mac, but 12 on Windows machine.

Is there a way to nest settings?
e.g.: 
```
{
   "settings": {
     "scopes": ["text.html.markdown"],
       "settings": {
            "platforms": ["osx"],
            "settings": {
                "font_size":10,
            }
            "platforms": ["windows"],
            "settings": {
                "font_size":12,
            }
       }
   }
}
```

**Comment by randy3k** [comment]
You just need to duplicate the settings. One entry for each platform.

**Comment by f8ttyc8t** [comment]
Thank you very much for quick reply!

But I still do not get the point how to obtain that.
I _try to_ get something like that:

MacOS:
 - Standard text: 10 points, Menlo, Monokai light
 - markdown: 11 points, Menlo, Monokai dark

Windows:
 - Standard text: 12 points, Calibri, gruvbox dark
 - markdown: 14 points, Calibri, gruvbox light

So I think I need nested settings. where specific settings depend on both platform as well as e.g. scope,

Any help is appreciated!

**Comment by randy3k** [comment]
something along this line
```
```
[
    {
        "scopes": ["text.html.markdown"],
        "platforms": ["osx"],
        "settings": {
            "font_size":10,
        }
    },
    {
        "scopes": ["text.html.markdown"],
        "platforms": ["linux"],
        "settings": {
            "font_size":12,
        }
    },    
]
```
```

may be the example was not clear to show that each entry can take more than one filter.

**Comment by f8ttyc8t** [comment]
Thank you!
That is exactly what I was searching for.

Best!
